# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_OPLUS_FEATURE_SCHED_ASSIST) += sched_assist/
obj-$(CONFIG_OPLUS_FEATURE_OPROJECT) += projectinfo/
obj-$(CONFIG_OPLUS_FEATURE_PHOENIX) += phoenix/
obj-$(CONFIG_OPLUS_DEVICE_IFNO) += device_info/
obj-$(CONFIG_OPLUS_FEATURE_MIDAS_V2) += midas/
