#!/bin/sh

# EVONIX_BUILD_IDENTITY_BEGIN
#
# Override Kleaf's reproducible placeholder identity for EVONIX builds.
: "${EVONIX_BUILD_USER:=NEESCHAL}"
: "${EVONIX_BUILD_HOST:=CODE}"

KBUILD_BUILD_USER="$EVONIX_BUILD_USER"
KBUILD_BUILD_HOST="$EVONIX_BUILD_HOST"

if test -n "$EVONIX_BUILD_TIMESTAMP"; then
	KBUILD_BUILD_TIMESTAMP="$EVONIX_BUILD_TIMESTAMP"
else
	KBUILD_BUILD_TIMESTAMP="$(TZ=Asia/Kathmandu date '+%a %b %d %H:%M:%S %z %Y')"
fi

export KBUILD_BUILD_USER
export KBUILD_BUILD_HOST
export KBUILD_BUILD_TIMESTAMP
# EVONIX_BUILD_IDENTITY_END

# SPDX-License-Identifier: GPL-2.0

UTS_MACHINE=$1
CC_VERSION="$2"
LD=$3

if test -z "$KBUILD_BUILD_USER"; then
	LINUX_COMPILE_BY=$(whoami | sed 's/\\/\\\\/')
else
	LINUX_COMPILE_BY=$KBUILD_BUILD_USER
fi
if test -z "$KBUILD_BUILD_HOST"; then
	LINUX_COMPILE_HOST=`uname -n`
else
	LINUX_COMPILE_HOST=$KBUILD_BUILD_HOST
fi

LD_VERSION=$(LC_ALL=C $LD -v | head -n1 |
		sed -e 's/(compatible with [^)]*)//' -e 's/[[:space:]]*$//')

cat <<EOF
#define UTS_MACHINE		"${UTS_MACHINE}"
#define LINUX_COMPILE_BY	"${LINUX_COMPILE_BY}"
#define LINUX_COMPILE_HOST	"${LINUX_COMPILE_HOST}"
#define LINUX_COMPILER		"${CC_VERSION}, ${LD_VERSION}"
EOF
